spring:
  application:
    name: smart-event-management

  datasource:
    url: jdbc:mysql://localhost:3306/sems_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update            # auto-creates/updates tables. Change to 'validate' in prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false           # best practice: disable OSIV to avoid lazy load issues

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8080

# JWT config (used starting Day 8)
jwt:
  secret: mySuper$ecretKey1234567890ABCDEFabcdefghij   # min 32 chars
  expiration: 86400000   # 24 hours in milliseconds

# Swagger UI path
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html